apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - secret.yaml
  - configmap.yaml
  - limitrange.yaml
  - resourcequota.yaml
  - networkpolicy.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - vpa.yaml
  - pdb.yaml
  - gateway.yaml
  - httproute.yaml
