apiVersion: v1
kind: Service
metadata:
  name: project-n-svc
  namespace: project-n
  labels:
    app.kubernetes.io/name: project-n
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: project-n
    app.kubernetes.io/managed-by: kubectl
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: project-n
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
